### ISSUE TITLE
Cookbook - Transaction refused while creating a schema definition

### ISSUE THREAD

**Issue by lanterno** [e-id-admin/public-sandbox-trustinfrastructure#22]
Hello,  I'm looking to get some assistance for my tests of the sandbox.
 
 I'm following the [cookbook](https://github.com/e-id-admin/public-sandbox-trustinfrastructure/tree/main/cookbook) trying to test my agent setup with the sandbox, and it's all smooth until the step "[2. Create a credential definition](https://github.com/e-id-admin/public-sandbox-trustinfrastructure/tree/main/cookbook#2-create-a-credential-definition)".

However, this step is not working. I checked the [sandbox](https://explorer.sandbox.ssi.ch/txs/SANDBOX/domain) and I could see my created schema there, but the definition is not being created. 

Logging at my agent logs, I saw this log: 

``` shell 

cookbook-issuer-1  | 2023-10-10 08:55:21,111 aries_cloudagent.transport.pack_format DEBUG Expanded message: 
{
   "@type":"did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/transactions/1.0/refuse",
   "@id":"405ce2ac-1a68-43c0-bef1-92ed3a9d1eef",
   "state":"transaction_refused",
   "transaction_id":"aa3b0839-5e5f-4ae1-8363-9ae75dd0bc53",
   "signature_response":{
      "message_id":"a1a9ca1e-6a01-4aad-9479-113673956669",
      "context":"did:sov",
      "method":"add-signature",
      "signer_goal_code":"aries.transaction.refuse"
   },
   "thread_id":"14261bd8-52b3-4065-ae68-f99114356b36"
}
```

you can find the latest schema I've created here: https://explorer.sandbox.ssi.ch/tx/SANDBOX/domain/338

Is there any advice on how I can debug this, or get more information on the exact reason behind the rejection?

**Comment by bit-jniestroj** [comment]
Hello @lanterno,

can you try it again? There was a missconfiguration in the public sandbox governance from our side. That was the reason why you can create a schema but no according cred defs for this schema.

**Comment by lanterno** [comment]
Hello @bit-jniestroj , 
   This solves it, and It's working well now, thanks!
